name: package

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  REGISTRY: ghcr.io

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: go test -v ./...
  build-and-push-latest-image:
    runs-on: ubuntu-latest
    needs:
      - linux
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image using Nix
        run: nix build .#docker && docker load < ./result
      - name: Push image
        run: docker push ghcr.io/aksiksi/ncdmv:latest
