name: Package

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      skip-docker-build: true
  build-and-push-amd64-image:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "system-features = big-parallel kvm"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image using Nix and load into Docker
        run: |
          nix build .#docker
          ./result | docker image load
          # Tag the image with the commit hash
          docker image tag ghcr.io/aksiksi/ncdmv:latest ghcr.io/aksiksi/ncdmv:${{ github.sha }}
      - name: Push image
        run: docker push -a ghcr.io/aksiksi/ncdmv
  build-and-push-arm64-image:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            system = aarch64-linux
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image using Nix and load into Docker
        run: |
          nix build .#docker
          ./result | docker image load
          # Tag the image with the commit hash
          docker image tag ghcr.io/aksiksi/ncdmv:latest ghcr.io/aksiksi/ncdmv:${{ github.sha }}
      # TODO(aksiksi): Re-add this once we've properly configured the Docker image
      # for multi-arch build. For now, we'll only published x64 images.
      #- name: Push image
      #  run: docker push -a ghcr.io/aksiksi/ncdmv
