name: Package

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  test:
    - uses: ./.github/workflows/test.yml
  build-and-push-latest-image:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "system-features = big-parallel kvm"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image using Nix and load into Docker
        run: |
          nix build .#docker
          ./result | docker image load
      - name: Push image
        run: docker push ghcr.io/aksiksi/ncdmv:latest
