name: Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: true
    - name: Run tests
      run: |
        nix-shell -p sqlite
        go test -v ./... -covermode=count -coverprofile=coverage.out
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
