name: Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
  workflow_call:
    inputs:
      skip-docker-build:
        type: boolean
        description: 'Skip Docker image build'

jobs:
  test:
    # Ubuntu 24.04 (latest) has issues with Chrome and AppArmor.
    # See: https://github.com/puppeteer/puppeteer/issues/12818
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: true
    - name: Run tests
      run: |
        nix-shell -p sqlite
        go test -v ./... -covermode=count -coverprofile=coverage.out
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
  build-docker-amd64-image:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.skip-docker-build }}
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build image using Nix and load into Docker
        run: |
          nix build .#docker
          ./result | docker image load
